# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 11:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Task')),
                ('due_to_date', models.DateField(default=datetime.date(2016, 9, 25), verbose_name='Due to')),
                ('description', models.TextField(verbose_name='Description')),
                ('reminder', models.DateTimeField(blank=True, null=True, verbose_name='Reminder')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
